---
title: "DE genes between organs"
output: html_notebook
---

```{r}
library(tidyverse)
library(batchelor)
library(Matrix)
library(SingleCellExperiment)
library(scran)
library(glue)
library(patchwork)
library(scater)
```

## Load pseudobulked data

```{r}
split = "LYMPHOID"
indir <- glue("/nfs/team205/ed6/data/Fetal_immune/LMM_data/DE_input_{split}_PBULK/")

matrix <- readMM(file = paste0(indir, "matrix.mtx.gz"))
coldata <- read.csv(file = paste0(indir, "metadata.csv.gz"))  %>%
  column_to_rownames("X")
rowdata <- read.csv(file = paste0(indir, "gene.csv.gz")) 

## Make SingleCellExperiment obj
sce <- SingleCellExperiment(list(counts = t(matrix)), colData = coldata)
rownames(sce) <- make.unique(rowdata$GeneName) 
sce <- logNormCounts(sce)
```

Load erythroid data for control

```{r}
ctrl_split = "MEM_PROGENITORS"
indir <- glue("/nfs/team205/ed6/data/Fetal_immune/LMM_data/DE_input_{ctrl_split}_PBULK/")

matrix <- readMM(file = paste0(indir, "matrix.mtx.gz"))
coldata <- read.csv(file = paste0(indir, "metadata.csv.gz"))  %>%
  column_to_rownames("X")
rowdata <- read.csv(file = paste0(indir, "gene.csv.gz")) 

## Make SingleCellExperiment obj
ctrl_sce <- SingleCellExperiment(list(counts = t(matrix)), colData = coldata)
rownames(ctrl_sce) <- make.unique(rowdata$GeneName) 
ctrl_sce <- logNormCounts(ctrl_sce)
```

```{r, fig.width=15, fig.height=10}
## Plot number of cells per organ/celltype pair
n_cells_heatmap <- data.frame(colData(sce)) %>%
  group_by(anno_lvl_2_final_clean, organ) %>%
  summarise(n_cells=sum(n_cells)) %>%
  ggplot(aes(anno_lvl_2_final_clean, organ)) +
  geom_tile(aes(fill=log10(n_cells))) +
  geom_text(aes(label=n_cells), color="white") +
  scale_fill_viridis_c() +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())

n_samples_heatmap <- data.frame(colData(sce)) %>%
  group_by(anno_lvl_2_final_clean, organ) %>%
  summarise(n_samples=n()) %>%
  ggplot(aes(anno_lvl_2_final_clean, organ)) +
  geom_tile(aes(fill=n_samples)) +
  geom_text(aes(label=n_samples), color="white") +
  scale_fill_viridis_c(option="cividis") +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))

n_cells_heatmap / n_samples_heatmap
```
```{r, fig.width=15, fig.height=10}
## Plot number of cells per organ/celltype pair
n_cells_heatmap <- data.frame(colData(ctrl_sce)) %>%
  group_by(anno_lvl_2_final_clean, organ) %>%
  summarise(n_cells=sum(n_cells)) %>%
  ggplot(aes(anno_lvl_2_final_clean, organ)) +
  geom_tile(aes(fill=log10(n_cells))) +
  geom_text(aes(label=n_cells), color="white") +
  scale_fill_viridis_c() +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())

n_samples_heatmap <- data.frame(colData(ctrl_sce)) %>%
  group_by(anno_lvl_2_final_clean, organ) %>%
  summarise(n_samples=n()) %>%
  ggplot(aes(anno_lvl_2_final_clean, organ)) +
  geom_tile(aes(fill=n_samples)) +
  geom_text(aes(label=n_samples), color="white") +
  scale_fill_viridis_c(option="cividis") +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))

n_cells_heatmap / n_samples_heatmap
```

## B cell progenitors - DE between liver and bone marrow

### Prepare dataset

```{r}
## Subset to Liver and Bone Marrow B cells
cts <- c('MATURE_B',"IMMATURE_B", "PRO_B", "PRE_PRO_B", "LATE_PRO_B", "SMALL_PRE_B", "LARGE_PRE_B", "CYCLING_B", "CD4+T", "CD8+T")
organs <- c("LI", "BM", "SP")
subset_sce <- sce[,sce$anno_lvl_2_final_clean %in% cts]
subset_sce <- subset_sce[,subset_sce$organ %in% organs]

## Feature selection w scran (just on test cts)
dec <- modelGeneVar(subset_sce)
hvgs <- getTopHVGs(dec, n = 7500)
subset_sce <- subset_sce[hvgs,]

ctrl_cts <- c("EARLY_ERY", "MID_ERY", "LATE_ERY")
subset_ctrl_sce <- ctrl_sce[,ctrl_sce$anno_lvl_2_final_clean %in% ctrl_cts]
subset_ctrl_sce <- subset_ctrl_sce[,subset_ctrl_sce$organ %in% organs]
subset_ctrl_sce <- subset_ctrl_sce[hvgs,]
subset_sce <- cbind(subset_sce, subset_ctrl_sce)

## Remove empty genes
non_empty_rows <- which(rowSums2(assay(subset_sce)) > 0)
subset_sce <- subset_sce[non_empty_rows,]

## Keep donors with paired organs in all the annotations
keep_donors <- 
  data.frame(colData(subset_sce)) %>%
  group_by(donor, anno_lvl_2_final_clean) %>%
  summarise(n_organs = length(unique(organ))) %>%
  filter(n_organs == length(organs) ) %>%
  # group_by(donor) %>%
  # summarise(n_anno=length(unique(anno_lvl_2_final_clean))) %>%
  # filter(n_anno == length(cts)) %>%
  pull(donor)

subset_sce <- subset_sce[,subset_sce$donor %in% keep_donors]

# Convert counts to dense matrix
counts(subset_sce) <- as.matrix(counts(subset_sce))

```

### Test for DE

```{r, fig.width=10, fig.height=10}
test_de_ct <- function(ct, de_res_ctrl, my_design, alpha_lev = 0.1){
  subset_sce$test_anno <- subset_sce$anno_lvl_2_final_clean == ct
  ## Check gene expression in tested celltype
  non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
  ct_subset_sce <- subset_sce[non_empty_rows,]
  ## Fit
  fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = c('SP'))
  de_res_1 <- test_de(fit, contrast = (`organLI` + `organLI:test_annoTRUE`) - (`organBM` + `organBM:test_annoTRUE`))
  de_res_1$lfc <- ifelse(abs(de_res_1$lfc) > 20, sign(de_res_1$lfc) * Inf, de_res_1$lfc)
  
  # de_res_1[,"lfc_ctrl"] <- de_res_ctrl$lfc
  # de_res_1[,"adj_pval_ctrl"] <- de_res_ctrl$adj_pval
  # de_res_1 <- mutate(de_res_1, signif=ifelse(adj_pval < alpha_lev & adj_pval_ctrl > alpha_lev, TRUE, FALSE)) 
  de_res_1[,'test_celltype'] <- ct
  return(de_res_1)
}

## Control (just btw organs)
my_design = ~ method + donor + organ + test_anno:organ + 1
subset_sce$test_anno <- subset_sce$anno_lvl_2_final_clean %in% c("LATE_ERY")
## Check gene expression in tested celltype
non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
ct_subset_sce <- subset_sce[non_empty_rows,]
## Fit
fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = c('SP'))
de_res_ctrl <- test_de(fit, contrast = (`organLI` + `organLI:test_annoTRUE`) - (`organBM` + `organBM:test_annoTRUE`))
de_res_ctrl$lfc <- ifelse(abs(de_res_ctrl$lfc) > 20, sign(de_res_ctrl$lfc) * Inf, de_res_ctrl$lfc)

test_cts <- c("PRE_PRO_B", 'PRO_B', "LATE_PRO_B", "LARGE_PRE_B")
de_res_ls <- lapply(test_cts, function(ct) test_de_ct(ct, de_res_ctrl, my_design))
de_res_ls <- setNames(de_res_ls, test_cts)
```


### Explore results

Check correlation between logFC values

```{r}
lfc_mat <- de_res_ls %>%
  purrr::reduce(bind_rows) %>%
  bind_rows(de_res_ctrl %>% mutate(test_celltype='control')) %>%
  select(lfc, test_celltype, name) %>%
  pivot_wider(names_from = 'test_celltype', values_from="lfc") %>%
  drop_na() %>%
  column_to_rownames('name') 

lfc_mat <- lfc_mat[!is.infinite(rowSums(lfc_mat)),]
corrplot::corrplot(cor(lfc_mat, method="spearman"), tl.col = 'black')
```

```{r, fig.height=6, fig.width=8}
library(UpSetR)
de_res_ls[['CTRL']] <- de_res_ctrl
deg_ls <- lapply(de_res_ls, function(x) x %>% filter(adj_pval < 0.1) %>% pull(name)) 
upset(fromList(deg_ls), order.by = c("freq"),
      sets.x.label = "# DEGs")
```
```{r, fig.height=12, fig.width=18}
plot_lfc_vs_ctrl <- function(de_res, min_lfc = 5, min_log10_pval = 5){
  ct <- de_res$test_celltype[1]
  de_res %>%
  mutate(signif = (adj_pval < 0.1)) %>%
  ggplot(aes(lfc_ctrl, lfc)) +
  geom_vline(xintercept = 0, linetype=2) + geom_hline(yintercept = 0, linetype=2) +
  geom_point(color="black", size=0.2) +
  geom_point(data = . %>% filter(signif), color='red', size=0.7) +
  ggrepel::geom_text_repel(data = . %>% filter(signif), 
                             aes(label=name), color='red',
                             max.overlaps=20) +
    ggtitle(ct) +
    theme_bw(base_size=18) +
    xlab("logFC CTRL") + ylab(glue("logFC ({ct} BM vs {ct} LI)"))
}

for (i in 1:4){
  d <- de_res_ls[[i]]
  d$lfc_ctrl <- column_to_rownames(de_res_ctrl, "name")[d$name,'lfc']  
  d$adj_pval_ctrl <- column_to_rownames(de_res_ctrl, "name")[d$name,'adj_pval']  
  de_res_ls[[i]] <- d
}

pl_ls <- lapply(de_res_ls[1:4], function(df) plot_lfc_vs_ctrl(df, min_lfc = 1, min_log10_pval = 1))
wrap_plots(pl_ls, ncol = 2)


```


```{r, fig.width=18, fig.height=12}
plot_volcano <- function(de_res, min_lfc = 5, min_log10_pval = 5){
  de_res %>%
    mutate(signif=adj_pval < 0.1) %>%
    ggplot(aes(lfc, -log10(adj_pval))) +
    geom_point(color="black", size=0.2) +
    geom_point(data = . %>% filter(signif), color='red', size=0.7) +
    ggrepel::geom_text_repel(data = . %>% filter(signif & abs(lfc) > min_lfc & -log10(adj_pval) > min_log10_pval), 
                             aes(label=name),
                             max.overlaps=20) +
    ggtitle(de_res$test_celltype[1]) +
    theme_bw(base_size=18) +
    xlab("logFC") + ylab("- log10(Adj. p-value)")
}

de_res_ls$CTRL[,'signif'] <-  de_res_ls$CTRL$adj_pval < 0.01
de_res_ls$CTRL[,'test_celltype'] <- "CTRL"
pl_ls <- lapply(de_res_ls, function(df) plot_volcano(df, min_lfc = 0.2, min_log10_pval = 1))
wrap_plots(pl_ls, ncol = 3)
```

### Save results
```{r}
de_res_ls %>%
  purrr::reduce(bind_rows) %>%
  bind_rows(de_res_ctrl %>% mutate(test_celltype='control')) %>%
  write_csv(paste0(indir, 'DE_results_Bprog_LIvsBM_ERYctrl.csv'))
```

## Thymic T cells

### Prepare dataset

```{r}
## Subset to Liver and Bone Marrow B cells
cts <- c("CD4+T", "CD8+T", "TREG")
subset_sce <- sce[,sce$anno_lvl_2_final_clean %in% cts]

## Feature selection w scran (just on test cts)
dec <- modelGeneVar(subset_sce)
hvgs <- getTopHVGs(dec, n = 7500)
subset_sce <- subset_sce[hvgs,]

ctrl_cts <- c('MATURE_B',"IMMATURE_B")
subset_ctrl_sce <- sce[,sce$anno_lvl_2_final_clean %in% ctrl_cts]
subset_ctrl_sce <- subset_ctrl_sce[hvgs,]
subset_sce <- cbind(subset_sce, subset_ctrl_sce)

subset_sce$organ <- ifelse(subset_sce$organ == 'TH', 'TH', 'other')
organs <- unique(subset_sce$organ)

## Remove empty genes
non_empty_rows <- which(rowSums2(assay(subset_sce)) > 0)
subset_sce <- subset_sce[non_empty_rows,]

## Keep donors with paired organs in all the annotations
keep_donors <- 
  data.frame(colData(subset_sce)) %>%
  group_by(donor, anno_lvl_2_final_clean) %>%
  summarise(n_organs = length(unique(organ))) %>%
  group_by(donor) %>%
  mutate(all(n_organs == length(organs) )) %>%
  # group_by(donor) %>%
  # summarise(n_anno=length(unique(anno_lvl_2_final_clean))) %>%
  # filter(n_anno == length(cts)) %>%
  pull(donor)

subset_sce <- subset_sce[,subset_sce$donor %in% keep_donors]

# Convert counts to dense matrix
counts(subset_sce) <- as.matrix(counts(subset_sce))

```

### Test for DE

```{r, fig.width=10, fig.height=10}
test_de_ct <- function(ct, de_res_ctrl, my_design, alpha_lev = 0.1){
  subset_sce$test_anno <- subset_sce$anno_lvl_2_final_clean == ct
  ## Check gene expression in tested celltype
  non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
  ct_subset_sce <- subset_sce[non_empty_rows,]
  ## Fit
  fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = c('other'))
  de_res_1 <- test_de(fit, contrast = (`organTH` + `organTH:test_annoTRUE`))
  de_res_1$lfc <- ifelse(abs(de_res_1$lfc) > 20, sign(de_res_1$lfc) * Inf, de_res_1$lfc)
  
  # de_res_1[,"lfc_ctrl"] <- de_res_ctrl$lfc
  # de_res_1[,"adj_pval_ctrl"] <- de_res_ctrl$adj_pval
  # de_res_1 <- mutate(de_res_1, signif=ifelse(adj_pval < alpha_lev & adj_pval_ctrl > alpha_lev, TRUE, FALSE)) 
  de_res_1[,'test_celltype'] <- ct
  return(de_res_1)
}

## Control (just btw organs)
my_design = ~ donor + organ + test_anno:organ + 1
subset_sce$test_anno <- subset_sce$anno_lvl_2_final_clean %in% c("MATURE_B")
## Check gene expression in tested celltype
non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
ct_subset_sce <- subset_sce[non_empty_rows,]

## Fit
fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = c('other'))
de_res_ctrl <- test_de(fit, contrast = (`organTH` + `organTH:test_annoTRUE`))
de_res_ctrl$lfc <- ifelse(abs(de_res_ctrl$lfc) > 20, sign(de_res_ctrl$lfc) * Inf, de_res_ctrl$lfc)

test_cts <- c("CD4+T", "CD8+T", "TREG")
de_res_ls <- lapply(test_cts, function(ct) test_de_ct(ct, de_res_ctrl, my_design))
de_res_ls <- setNames(de_res_ls, test_cts)

```

### Explore results

Check correlation between logFC values

```{r}
lfc_mat <- de_res_ls %>%
  purrr::reduce(bind_rows) %>%
  bind_rows(de_res_ctrl %>% mutate(test_celltype='control')) %>%
  select(lfc, test_celltype, name) %>%
  pivot_wider(names_from = 'test_celltype', values_from="lfc") %>%
  drop_na() %>%
  column_to_rownames('name') 

lfc_mat <- lfc_mat[!is.infinite(rowSums(lfc_mat)),]
corrplot::corrplot(cor(lfc_mat, method="spearman"), tl.col = 'black')

```
```{r, fig.height=6, fig.width=8}
de_res_ls[['CTRL']] <- de_res_ctrl
deg_ls <- lapply(de_res_ls, function(x) x %>% filter(adj_pval < 0.1) %>% pull(name)) 
upset(fromList(deg_ls), order.by = c("freq"),
      sets.x.label = "# DEGs")
```

```{r, fig.height=12, fig.width=18}
plot_lfc_vs_ctrl <- function(de_res, min_lfc = 5, min_log10_pval = 5){
  ct <- de_res$test_celltype[1]
  de_res %>%
  mutate(signif = (adj_pval < 0.1)) %>%
  ggplot(aes(lfc_ctrl, lfc)) +
  geom_vline(xintercept = 0, linetype=2) + geom_hline(yintercept = 0, linetype=2) +
  geom_point(color="black", size=0.2) +
  geom_point(data = . %>% filter(signif), color='red', size=0.7) +
  geom_text(data = . %>% filter(signif & abs(lfc) > min_lfc & -log10(adj_pval) > min_log10_pval), 
                             aes(label=name),
                             max.overlaps=20) +
    ggtitle(ct) +
    theme_bw(base_size=18) +
    xlab("logFC CTRL") + ylab(glue("logFC ({ct} BM vs {ct} LI)"))
}

for (i in 1:4){
  d <- de_res_ls[[i]]
  d$lfc_ctrl <- column_to_rownames(de_res_ctrl, "name")[d$name,'lfc']  
  d$adj_pval_ctrl <- column_to_rownames(de_res_ctrl, "name")[d$name,'adj_pval']  
  de_res_ls[[i]] <- d
}

pl_ls <- lapply(de_res_ls[1:3], function(df) plot_lfc_vs_ctrl(df,min_lfc = 5, min_log10_pval = 5))
pl_ls[[1]]
wrap_plots(pl_ls, ncol = 3)
plot_lfc_vs_ctrl(de_res_ls[[1]])

```
---

```{r}
de_res <- de_res_ls$PRE_PRO_B
degs <- de_res %>% filter(signif & lfc > 0) %>%
  filter(!is.infinite(lfc)) %>%
  arrange(-lfc) %>% pull(name) %>% {.[0:20]}
ct <- de_res$test_celltype[1]

assay(subset_sce, 'corrected_counts') <- (counts(subset_sce)/colSums(counts(subset_sce)))*10000
tmp <- reshape2::melt(assay(subset_sce, 'corrected_counts')[degs,], varnames=c("gene", "rowname")) %>%
  left_join(data.frame(colData(subset_sce)) %>% rownames_to_column()) %>%
  mutate(test_ct=anno_lvl_2_final_clean == ct) %>%
  filter(organ %in% c('BM', "LI") & test_ct) 

ggplot(tmp, aes(x = organ, y = log1p(value), color=test_ct)) +
  geom_jitter(width = 0.2) +
  stat_summary(data=. %>% filter(test_ct), geom = "crossbar", fun = "mean", color = "red") +
  facet_wrap(~ gene, scales = "free_y") 

```
```{r, fig.width=10, fig.height=10}
de_res <- de_res_ctrl
degs <- de_res %>% filter(pval > 0.9) %>%
  # filter(!is.infinite(lfc)) %>%
  # arrange(lfc) %>% 
  pull(name) %>% {.[0:30]}
ct <- "LATE_ERY"

tmp <- reshape2::melt(assay(subset_sce, 'counts')[degs,], varnames=c("gene", "rowname")) %>%
  left_join(data.frame(colData(subset_sce)) %>% rownames_to_column()) %>%
  mutate(test_ct=anno_lvl_2_final_clean == ct) %>%
  filter(organ %in% c('BM', "LI") & test_ct) 

ggplot(tmp, aes(x = organ, y = value, color=test_ct)) +
  geom_point() +
  geom_jitter(width = 0.2, height = 0) +
  # stat_summary(data=. %>% filter(test_ct), geom = "crossbar", fun = "mean", color = "red") +
  facet_wrap(~ gene, scales = "free_y") 

```