---
title: "DE genes between organs"
output: html_notebook
---

```{r}
library(tidyverse)
library(batchelor)
library(Matrix)
library(SingleCellExperiment)
library(scran)
library(glue)
library(patchwork)
library(scater)
library(glmGamPoi)
```

## Load pseudobulked data

```{r}
split = "PROGENITORS"
indir <- glue("/nfs/team205/ed6/data/Fetal_immune/LMM_data/DE_input_{split}_PBULK/")

matrix <- readMM(file = paste0(indir, "matrix.mtx.gz"))
coldata <- read.csv(file = paste0(indir, "metadata.csv.gz"))  %>%
  column_to_rownames("X")
rowdata <- read.csv(file = paste0(indir, "gene.csv.gz")) 

## Make SingleCellExperiment obj
sce <- SingleCellExperiment(list(counts = t(matrix)), colData = coldata)
rownames(sce) <- make.unique(rowdata$GeneName) 
sce <- logNormCounts(sce)
sce
```

<!-- Load erythroid data for control -->

<!-- ```{r} -->
<!-- ctrl_split = "MEM_PROGENITORS" -->
<!-- indir <- glue("/nfs/team205/ed6/data/Fetal_immune/LMM_data/DE_input_{ctrl_split}_PBULK/") -->

<!-- matrix <- readMM(file = paste0(indir, "matrix.mtx.gz")) -->
<!-- coldata <- read.csv(file = paste0(indir, "metadata.csv.gz"))  %>% -->
<!--   column_to_rownames("X") -->
<!-- rowdata <- read.csv(file = paste0(indir, "gene.csv.gz"))  -->

<!-- ## Make SingleCellExperiment obj -->
<!-- ctrl_sce <- SingleCellExperiment(list(counts = t(matrix)), colData = coldata) -->
<!-- rownames(ctrl_sce) <- make.unique(rowdata$GeneName)  -->
<!-- ctrl_sce <- logNormCounts(ctrl_sce) -->
<!-- ``` -->

```{r, fig.width=10, fig.height=10}
## Plot number of cells per organ/celltype pair
n_cells_heatmap <- data.frame(colData(sce)) %>%
  group_by(prog_lineage, organ) %>%
  summarise(n_cells=sum(n_cells)) %>%
  ggplot(aes(prog_lineage, organ)) +
  geom_tile(aes(fill=log10(n_cells))) +
  geom_text(aes(label=n_cells), color="white") +
  scale_fill_viridis_c() +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())

n_samples_heatmap <- data.frame(colData(sce)) %>%
  group_by(prog_lineage, organ) %>%
  summarise(n_samples=n()) %>%
  ggplot(aes(prog_lineage, organ)) +
  geom_tile(aes(fill=n_samples)) +
  geom_text(aes(label=n_samples), color="white") +
  scale_fill_viridis_c(option="cividis") +
  theme_classic(base_size = 16) +
  xlab("celltype") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=0.5))

n_cells_heatmap / n_samples_heatmap
```
```{r}
sce$organ <- ifelse(sce$organ %in% c("SK", "GU", "KI"), 'peripheral_organs', sce$organ)
```

<!-- ```{r} -->
<!-- progenitor_groups = list( -->
<!--      'HSC_MPP_LMP'=c("HSC_MPP", "CYCLING_MPP", "LMPP_MLP"), -->
<!--     'T_prog'     =c("DN(early)_T","DN(Q)_T", "DN(P)_T"), -->
<!--     'B_prog'     =c('PRE_PRO_B', 'PRO_B','LATE_PRO_B','LARGE_PRE_B','SMALL_PRE_B'), -->
<!--     'MEM_prog'   =c('MEMP', 'CYCLING_MEMP', 'MEP', "EARLY_MK"), -->
<!--     'MYE_prog'   =c('CMP','DC_PROGENITOR','GMP','MOP','MYELOCYTE','PROMONOCYTE','PROMYELOCYTE') -->
<!-- ) -->


<!-- prog_sce <- sce[,sce$anno_lvl_2_final_clean %in% unlist(progenitor_groups)] -->
<!-- prog_group_mat <- sapply(progenitor_groups, function(x) prog_sce$anno_lvl_2_final_clean %in% x) -->
<!-- prog_sce$prog_group <- apply(prog_group_mat, 1, function(x) ifelse(any(x), names(progenitor_groups)[which.max(x)], 0)) -->
<!-- ``` -->

## PCA
```{r, fig.width=12, fig.height=6}
library(scran)
## Feature selection w scran (just on test cell types)
n_hvgs = 5000
dec <- modelGeneVar(sce)
hvgs <- getTopHVGs(dec, n = n_hvgs)
subset_sce <- sce[hvgs,]

sce <- runPCA(sce) 
plotPCA(sce, colour_by='organ', ncomponents=2) +
plotPCA(sce, colour_by='method', ncomponents=4) 
```


## Helper functions

```{r}
## Prepare dataset subset for DE analysis
de_prep_data <- function(sce,
                        cts, ## Which celltypes to test 
                         organ_test, ## Which organ to test
                         organ_ctrl=NULL, ## Which organ to compare to (if NULL compare organ VS rest)
                         organ_ref=NULL, ## Which organ to use as reference
                         n_hvgs = 7500
  ){
    # if ( is.null(organ_ctrl) ){
    #   organs <- c(organ_test, "other")
    #   sce$organ <- ifelse(sce$organ == organ_test, organ_test, 'other')
    # } else {
    #   organs <- c(organ_test, organ_ctrl, organ_ref)
    # }
  
    subset_sce <- sce[,sce$prog_lineage %in% cts]
    # subset_sce <- subset_sce[,subset_sce$organ %in% organs]
    
    ## Keep donors with paired organs in all the annotations
    keep_donors <- 
      data.frame(colData(subset_sce)) %>%
      group_by(donor, prog_lineage) %>%
      summarise(n_organs = length(unique(organ))) %>%
      filter(n_organs == length(organs) ) %>%
      pull(donor) %>% unique()
    
    subset_sce <- subset_sce[,subset_sce$donor %in% keep_donors]

    ## Feature selection w scran (just on test cell types)
    dec <- modelGeneVar(subset_sce)
    hvgs <- getTopHVGs(dec, n = n_hvgs)
    subset_sce <- subset_sce[hvgs,]
    
    # ## Find control celltypes
    # matched_donor_df <- data.frame(colData(sce[,sce$donor %in% keep_donors]))
    # # if ( is.null(organ_ctrl) ){ matched_donor_df$organ <- ifelse(matched_donor_df$organ == organ_test, organ_test, 'other') }
    # ctrl_cts <- matched_donor_df %>%
    #   filter(organ %in% organs & (!prog_lineage %in% cts)) %>%
    #   group_by(prog_lineage, organ) %>%
    #   summarise(n=n(), n_cells=sum(n_cells)) %>%
    #   group_by(prog_lineage) %>%
    #   filter(all(n > 2) & all(n_cells > 50)) %>%
    #   summarise(n_organs=n(), mean_n_cells = mean(n_cells), mean_n=mean(n)) %>%
    #   filter(n_organs == length(organs)) %>%
    #   arrange(-mean_n_cells) %>%
    #   # filter(!prog_lineage %in% anno_groups$`NK/T CELLS`) %>% ## Exclude other T cell subtypes
    #   pull(prog_lineage) %>% unique()
    
    # subset_ctrl_sce <- sce[,sce$prog_lineage %in% ctrl_cts[1:3]]
    # # if ( is.null(organ_ctrl) ){ subset_ctrl_sce$organ <- ifelse(subset_ctrl_sce$organ == organ_test, organ_test, 'other') }
    # subset_ctrl_sce <- subset_ctrl_sce[,subset_ctrl_sce$organ %in% organs]
    # subset_ctrl_sce <- subset_ctrl_sce[hvgs,]
    # subset_sce <- cbind(subset_sce, subset_ctrl_sce)
    # 
    # ## Mark control celltypes
    # subset_sce$is_ctrl_ct <- subset_sce$prog_lineage %in% ctrl_cts[1:3]
    
    # Convert counts to dense matrix
    counts(subset_sce) <- as.matrix(counts(subset_sce))
    return(subset_sce)
}

test_de_ct <- function(subset_sce, test_cts, ctrl_cts, contrast_str, 
                       organ_ref = 'other',alpha_lev = 0.1, max_lfc = 20){
  cts <- c(test_cts, ctrl_cts)
  condition <- c(rep("ct_test", length(test_cts)), rep("ct_ctrl", length(ctrl_cts)))
  subset_sce$prog_lineage <- factor(subset_sce$prog_lineage, levels=rev(cts))
  my_design = ~ 1 + donor + organ + prog_lineage + prog_lineage:organ 
  
  ## Fit
  fit <- glm_gp(subset_sce, design = my_design, reference_level = organ_ref)
  
  ## Test 
  de_res_ls <- lapply(cts[1:length(cts)-1], function(ct){ 
    my_contrast <- glue(contrast_str)
    de_res <- test_de(fit, contrast = eval(parse(text=my_contrast)))
    de_res$lfc <- ifelse(abs(de_res$lfc) > max_lfc, sign(de_res$lfc) * Inf, de_res$lfc)
    de_res[,'test_celltype'] <- ct
    return(de_res)
    })
  
  return(de_res_ls)
}

# 
# ## DE testing in celltype of interest
# test_de_ct <- function(subset_sce, ct, my_design, my_contrast, organ_ref = 'other',alpha_lev = 0.1, max_lfc = 20){
#   ## Exclude genes not expressed in tested celltype
#   subset_sce$test_anno <- subset_sce$prog_lineage == ct
#   non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
#   ct_subset_sce <- subset_sce[non_empty_rows,]
#   
#   ## Fit
#   fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = organ_ref)
#   
#   ## Test condition
#   de_res_1 <- test_de(fit, contrast = eval(parse(text=my_contrast)))
#   de_res_1$lfc <- ifelse(abs(de_res_1$lfc) > max_lfc, sign(de_res_1$lfc) * Inf, de_res_1$lfc)
#   
#   de_res_1[,'test_celltype'] <- ct
#   return(de_res_1)
# }
# 
# ## DE testing in control celltypes (to account for background expression)
# test_de_ctrl_ct <- function(subset_sce, my_design, my_contrast, organ_ref = 'other',alpha_lev = 0.1, max_lfc = 20){
#   subset_sce$test_anno <- subset_sce$prog_lineage %in% unique(subset_sce$prog_lineage[subset_sce$is_ctrl_ct])
#   ## Check gene expression in tested celltype
#   non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$test_anno])) > 0)
#   ct_subset_sce <- subset_sce[non_empty_rows,]
#   
#   ## Fit
#   fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = organ_ref)
#   de_res_ctrl <- test_de(fit, contrast = eval(parse(text=my_contrast)))
#   de_res_ctrl$lfc <- ifelse(abs(de_res_ctrl$lfc) > 10, sign(de_res_ctrl$lfc) * Inf, de_res_ctrl$lfc)
#   return(de_res_ctrl) 
#   }

## Save annotation of significant genes to follow up on
mark_significant <- function(de_res, de_res_ctrl, lfc_thresh=3, alpha_thresh=0.1){
  de_res_ctrl <- as.data.frame(de_res_ctrl)
  rownames(de_res_ctrl) <- de_res_ctrl$name
  de_res$lfc_ctrl <- de_res_ctrl[de_res$name,'lfc']
  mark_signif <- 
    (de_res$adj_pval < alpha_thresh) &
    (abs(de_res$lfc_ctrl) < lfc_thresh) &
    (abs(de_res$lfc) >= lfc_thresh) 
  de_res$filter_signif <- mark_signif
  return(de_res)
  }

plot_deg <- function(res_all, gene, org, min_lfc = 1, alpha=0.1){
  degs <- res_all %>%
    filter((abs(lfc) | is.infinite(abs(lfc )) > min_lfc) & (adj_pval < alpha) & (test_organ==org)) %>%
    pull(name)

  deg_df <- data.frame(logcounts(ct_subset_sce[degs,]) %>% as.matrix() %>% t)
  colnames(deg_df) <- degs
  pl_df <- cbind(colData(ct_subset_sce) %>% data.frame(), deg_df)

  pl_df[,'gene_oi'] <- pl_df[,gene]
  pl_df %>%
    mutate(organ=factor(organ, levels=test_organs)) %>%
    drop_na() %>%
    ggplot(aes(organ,gene_oi, , color=organ)) +
    geom_boxplot() +
    ylab(gene) +
    theme_bw(base_size=18) +
    geom_jitter() 
    
  }

```


## MEM progenitors

```{r}
## Prep data subset for testing
organ_test <- unique(sce$organ)
organ_ctrl <- NULL

test_cts <- c("MEM_prog")
max_lfc <- 20

subset_sce <- sce
subset_sce$organ <- ifelse(subset_sce$organ %in% c("MLN", "TH", "SP"), 'lymphoid_organ', subset_sce$organ )
subset_sce$prog_lineage <- ifelse(subset_sce$prog_lineage == test_cts, test_cts, 'other')

## Feature selection w scran (just on test cell types)
dec <- modelGeneVar(subset_sce)
hvgs <- getTopHVGs(dec, n = 7500)
subset_sce <- subset_sce[hvgs,]
counts(subset_sce) <- as.matrix(counts(subset_sce))

non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$prog_lineage == test_cts])) > 0)
ct_subset_sce <- subset_sce[non_empty_rows,]

# subset_sce$prog_lineage <- factor(subset_sce$prog_lineage, levels=rev(cts))
# my_design = ~ donor + prog_lineage + organ  + prog_lineage:organ 

my_design = ~ prog_lineage + organ + prog_lineage:organ
contrast_str <- "`organ{org}` + `prog_lineage{test_cts}:organ{org}`"
ct_subset_sce$prog_lineage <- factor(ct_subset_sce$prog_lineage, levels=c('other', test_cts))
fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = 'peripheral_organs')


test_organs <- c("YS", "LI", "BM", 'lymphoid_organ')

de_res_ls <- lapply(test_organs, function(org){ 
    my_contrast <- glue(contrast_str)
    de_res <- test_de(fit, contrast = eval(parse(text=my_contrast)))
    de_res$lfc <- ifelse(abs(de_res$lfc) > max_lfc, sign(de_res$lfc) * Inf, de_res$lfc)
    de_res[,'test_organ'] <- org
    de_res[,'test_ct'] <- test_cts[1]
    return(de_res)
    })

res_all <- de_res_ls %>%
  purrr::reduce(bind_rows)
```



```{r}
min_lfc = 1; alpha=0.1
up_genes <- res_all %>%
  filter((lfc > min_lfc | lfc == Inf ) & (adj_pval < alpha)) 

down_genes <- res_all %>%
  filter((lfc < - min_lfc | lfc == -Inf ) & (adj_pval < alpha)) 

org_specific_up <- up_genes %>%
  group_by(name) %>%
  summarise(n_organs_up=n())  %>%
  filter(n_organs_up < 4) %>%
  pull(name)

org_specific_down <- down_genes %>%
  group_by(name) %>%
  summarise(n_organs_down=n())  %>%
  filter(n_organs_down < 3) %>%
  pull(name)

org_specific_up
```


```{r, fig.width=18, fig.height=12}

res_all %>%
  mutate(test_organ=factor(test_organ, levels=test_organs)) %>%
  mutate(label=ifelse((adj_pval < 0.1) & (abs(lfc) > 1) & (name %in% c(org_specific_down, org_specific_up)), name, NA)) %>%
  ggplot(aes(lfc, - log10(adj_pval))) +
  geom_point(size = 0.5) +
  ggrepel::geom_text_repel(aes(label=label)) +
  geom_hline(yintercept=1, color='red', linetype=2) +
  facet_wrap(test_organ~., scales='free') +
  theme_bw(base_size=18) +
  ggtitle("B progenitors") + 
  ggsave("~/mount/gdrive/Pan_fetal/Updates_and_presentations/revision/MEM_prog_DEGs.pdf", width=12, height=9)
```

```{r}
plot_deg(res_all, "CD52", "BM")
```

```{r}
write_csv(res_all, paste0(indir, 'DEGS_MEM_prog.csv'))
```

## B cell progenitors

```{r}
## Prep data subset for testing
organ_test <- unique(sce$organ)
organ_ctrl <- NULL

test_cts <- c("B_prog")
max_lfc <- 20

subset_sce <- sce
subset_sce$prog_lineage <- ifelse(subset_sce$prog_lineage == test_cts, test_cts, 'other')

## Feature selection w scran (just on test cell types)
dec <- modelGeneVar(subset_sce)
hvgs <- getTopHVGs(dec, n = 7500)
subset_sce <- subset_sce[hvgs,]
counts(subset_sce) <- as.matrix(counts(subset_sce))

non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$prog_lineage == test_cts])) > 0)
ct_subset_sce <- subset_sce[non_empty_rows,]

# subset_sce$prog_lineage <- factor(subset_sce$prog_lineage, levels=rev(cts))
# my_design = ~ donor + prog_lineage + organ  + prog_lineage:organ 

my_design = ~ prog_lineage + organ + prog_lineage:organ
contrast_str <- "`organ{org}` + `prog_lineage{test_cts}:organ{org}`"
ct_subset_sce$prog_lineage <- factor(ct_subset_sce$prog_lineage, levels=c('other', test_cts))
fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = 'MLN')

colnames(fit$model_matrix)

test_organs <- c("YS", "LI", "BM","TH",  'SP',"peripheral_organs")

de_res_ls <- lapply(test_organs, function(org){ 
    my_contrast <- glue(contrast_str)
    de_res <- test_de(fit, contrast = eval(parse(text=my_contrast)))
    de_res$lfc <- ifelse(abs(de_res$lfc) > max_lfc, sign(de_res$lfc) * Inf, de_res$lfc)
    de_res[,'test_organ'] <- org
    de_res[,'test_ct'] <- test_cts[1]
    return(de_res)
    })

res_all <- de_res_ls %>%
  purrr::reduce(bind_rows)
```



```{r}
min_lfc = 1; alpha=0.1
up_genes <- res_all %>%
  filter((lfc > min_lfc | lfc == Inf ) & (adj_pval < alpha)) 

down_genes <- res_all %>%
  filter((lfc < - min_lfc | lfc == -Inf ) & (adj_pval < alpha)) 

org_specific_up <- up_genes %>%
  group_by(name) %>%
  summarise(n_organs_up=n())  %>%
  filter(n_organs_up < 4) %>%
  pull(name)

org_specific_down <- down_genes %>%
  group_by(name) %>%
  summarise(n_organs_down=n())  %>%
  filter(n_organs_down < 4) %>%
  pull(name)

org_specific_up
```


```{r, fig.width=18, fig.height=12}

res_all %>%
  mutate(test_organ=factor(test_organ, levels=test_organs)) %>%
  mutate(label=ifelse((adj_pval < 0.1) & (abs(lfc) > 1) & (name %in% c(org_specific_down, org_specific_up)), name, NA)) %>%
  ggplot(aes(lfc, - log10(adj_pval))) +
  geom_point(size = 0.5) +
  ggrepel::geom_text_repel(aes(label=label)) +
  geom_hline(yintercept=1, color='red', linetype=2) +
  facet_wrap(test_organ~., scales='free') +
  theme_bw(base_size=18) +
  ggtitle("B progenitors") + 
  ggsave("~/mount/gdrive/Pan_fetal/Updates_and_presentations/revision/B_prog_DEGs.pdf", width=12, height=9)
```
```{r}
plot_deg(res_all, "HYAL2", "LI")
```

```{r}
write_csv(res_all, paste0(indir, 'DEGS_B_prog.csv'))
```

```{r, fig.width=4, fig.height=24}
degs <- c(org_specific_up, org_specific_down)

lfc_mat <- res_all %>%
  filter(name %in% degs) %>%
  mutate(lfc = ifelse(adj_pval > 0.1, 0, lfc)) %>%
  pivot_wider(id_cols=name, values_from=lfc, names_from=test_organ) %>%
  column_to_rownames('name') %>%
  as.matrix()

lfc_mat <- lfc_mat[rowSums(is.infinite(lfc_mat)) < ncol(lfc_mat),]
lfc_mat[lfc_mat == Inf] <- 10
lfc_mat[lfc_mat == -Inf] <- -10
pheatmap::pheatmap((lfc_mat), fontsize_row = 6)
```

```{r}

```

## Myeloid progenitors

```{r}
## Prep data subset for testing
organ_test <- unique(sce$organ)
organ_ctrl <- NULL

test_cts <- c("MYE_prog")
max_lfc <- 20

subset_sce <- sce
subset_sce$prog_lineage <- ifelse(subset_sce$prog_lineage == test_cts, test_cts, 'other')

## Feature selection w scran (just on test cell types)
dec <- modelGeneVar(subset_sce)
hvgs <- getTopHVGs(dec, n = 7500)
subset_sce <- subset_sce[hvgs,]
counts(subset_sce) <- as.matrix(counts(subset_sce))

non_empty_rows <- which(rowSums2(counts(subset_sce[,subset_sce$prog_lineage == test_cts])) > 0)
ct_subset_sce <- subset_sce[non_empty_rows,]

# subset_sce$prog_lineage <- factor(subset_sce$prog_lineage, levels=rev(cts))
# my_design = ~ donor + prog_lineage + organ  + prog_lineage:organ 

my_design = ~ prog_lineage + organ + prog_lineage:organ
contrast_str <- "`organ{org}` + `prog_lineage{test_cts}:organ{org}`"
ct_subset_sce$prog_lineage <- factor(ct_subset_sce$prog_lineage, levels=c('other', test_cts))
fit <- glm_gp(ct_subset_sce, design = my_design, reference_level = 'MLN')

colnames(fit$model_matrix)

test_organs <- c("YS", "LI", "BM","TH",  'SP',"peripheral_organs")

de_res_ls <- lapply(test_organs, function(org){ 
    my_contrast <- glue(contrast_str)
    de_res <- test_de(fit, contrast = eval(parse(text=my_contrast)))
    de_res$lfc <- ifelse(abs(de_res$lfc) > max_lfc, sign(de_res$lfc) * Inf, de_res$lfc)
    de_res[,'test_organ'] <- org
    de_res[,'test_ct'] <- test_cts[1]
    return(de_res)
    })

res_all <- de_res_ls %>%
  purrr::reduce(bind_rows)
```



```{r}
min_lfc = 1; alpha=0.1
up_genes <- res_all %>%
  filter((lfc > min_lfc | lfc == Inf ) & (adj_pval < alpha)) 

down_genes <- res_all %>%
  filter((lfc < - min_lfc | lfc == -Inf ) & (adj_pval < alpha)) 

org_specific_up <- up_genes %>%
  group_by(name) %>%
  summarise(n_organs_up=n())  %>%
  filter(n_organs_up < 4) %>%
  pull(name)

org_specific_down <- down_genes %>%
  group_by(name) %>%
  summarise(n_organs_down=n())  %>%
  filter(n_organs_down < 4) %>%
  pull(name)

org_specific_up
```


```{r, fig.width=18, fig.height=12}

res_all %>%
  mutate(test_organ=factor(test_organ, levels=test_organs)) %>%
  mutate(label=ifelse((adj_pval < 0.1) & (abs(lfc) > 1) & (name %in% c(org_specific_down, org_specific_up)), name, NA)) %>%
  ggplot(aes(lfc, - log10(adj_pval))) +
  geom_point(size = 0.5) +
  ggrepel::geom_text_repel(aes(label=label)) +
  geom_hline(yintercept=1, color='red', linetype=2) +
  facet_wrap(test_organ~., scales='free') +
  theme_bw(base_size=18) +
  ggtitle("B progenitors") + 
  ggsave("~/mount/gdrive/Pan_fetal/Updates_and_presentations/revision/MYE_prog_DEGs.pdf", width=12, height=9)
```
```{r}
plot_deg(res_all, "CD27", "peripheral_organs")
```
```{r}
write_csv(res_all, paste0(indir, 'DEGS_MYE_prog.csv'))
```

---



---
